name: Android Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease
        
      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: " app/build/outputs/apk/release/*.apk,app/build/outputs/apk/release/*.aab"
          tag: v1.0.${{ github.run_number }}
